# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3db31627bdab44b5dd4abb579976e49d11a5de56863985e373e27810c25c7deee7943b84ecd05fce5e099f095a2c8b4ab73765a278f2157e692b1ef1a4dfe588
  GOOGLE_KEY: '504981975584-lo761bhm66hcri25br4mg9hcdjn6h153.apps.googleusercontent.com'
  GOOGLE_SECRET: 'GgszwI6Xd66KuYYCIoKGefB6'
  FB_KEY: '465165247233809'
  FB_SECRET: 'd3ce08d04358c575d240899a6c5af8da'
  TWITTER_KEY: 'ucmNFKoZ6VwhDL6bGmclkhxR1'
  TWITTER_SECRET: 'AgM2zv999g0ttEt0bzpbATHGoLwD4uhupNHi4icwn9hGudVpaK'

test:
  secret_key_base: b8f50691e906bf6a9f21b7ab118d42d9fa9e0d93462514a259ab68eedb33b87fb062a08c2361418be2f4f025f2da1b4823549131151d2f36b84661c715489587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
